spring.application.name=Internship_project
spring.main.allow-bean-definition-overriding=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/internship_project
spring.datasource.username=postgres
spring.datasource.password=admin


testing.app.secret=test 
testing.app.lifetime=60000